Add DynamoDB table delete pipeline
turbot/flowpipe-mod-aws-thrifty pull request #34
Opened 2024-05-15 09:47 UTC by khushboo9024

2024-05-16 18:16 UTC, graza-io commented on dynamodb/dynamodb_table_stale_data.fp
> +  // documentation = file("./dynamodb/docs/correct_one_dynamodb_table_stale_data_exceeding_max_age.md")
Shouldn't be commented out

2024-05-16 18:17 UTC, graza-io commented on dynamodb/dynamodb_table_stale_data.fp
> +      detect_msg         = "Detected Dynamodb table stale data  ${param.title} exceeding maximum age."
Should be `DynamoDB` as per other references?

2024-05-16 18:17 UTC, graza-io commented on dynamodb/dynamodb_table_stale_data.fp
> +          error_msg   = "Error deleting Dynamodb table ${param.title}."
Should be DynamoDB as per other references?

2024-05-16 18:18 UTC, graza-io commented on thrifty.fpvars.example
> +dynamodb_table_stale_data_exceeding_max_age_default_action   = "delete_table"
Value should be `"notify"`, allowing the user to override it but we shouldn't outright delete anything automatically out of the box.

2024-05-16 18:20 UTC, graza-io requested changes
See comments.

Additionally @misraved - I feel like the wording is wrong here: "stale data exceeding max age"... perhaps reads better as "with stale data", thoughts?

2024-05-17 09:04 UTC, misraved commented
@graza-io agreed, I think `with_stale_data` is self-explanatory and we should go with it 👍.

2024-05-17 13:46 UTC, graza-io approved these changes

2024-05-17 14:16 UTC, merged